version: '2'
services:
  db:
    image: postgres
    container_name: boilerplate_postgres
    ports:
      - 54329:5432
    volumes:
      - ./provision/db/:/docker-entrypoint-initdb.d
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6379:6379